version: "3.9"

services:
  haioo-cart-postgree:
    container_name: haioo-cart-postgree
    image: postgres:14.1-alpine
    restart: always
    networks:
      - go-cqrs
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes: 
      - db:/var/lib/postgresql/data

  haioo-cart-redis:
    container_name: haioo-cart-redis
    image: redis:6.2-alpine
    restart: always
    networks:
      - go-cqrs
    ports:
      - 6379:6379
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes: 
      - cache:/data


volumes:
  db:
    driver: local
  cache:
    driver: local

networks:
  go-cqrs:
    driver: bridge
